site_name: Cloudmesh AI Vpn
docs_dir: docs
use_directory_urls: false
theme:
  name: material
  logo: assets/logo-white.png
  favicon: assets/favicon.ico
extra_css:
- css/custom.css
nav:
- Home: index.md
- Technology:  technology.md
- Project:
  - Changelog: CHANGELOG.md
  - GitHub: https://github.com/cloudmesh-ai/cloudmesh-ai-vpn
  - Issues: https://github.com/cloudmesh-ai/cloudmesh-ai-vpn/issues
- API Reference: api.md
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        paths:
        - src
        options:
          docstring_style: google
          show_submodules: true
          members: true
          docstring_section_style: table
          show_source: true
          group_by_category: true
          show_category_heading: true
          separate_signature: true
          show_root_full_path: true
