docs_dir: docs
extra_css:
- css/custom.css
nav:
- Home: index.md
- Technology: technology.md
- Project:
  - Changelog: CHANGELOG.md
  - GitHub: https://github.com/cloudmesh-ai/cloudmesh-ai-vpn
  - Issues: https://github.com/cloudmesh-ai/cloudmesh-ai-vpn/issues
- API Reference: api.md
- commands: commands.md
- README: README.md
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          docstring_section_style: table
          docstring_style: google
          group_by_category: true
          members: true
          separate_signature: true
          show_category_heading: true
          show_root_full_path: true
          show_source: true
          show_submodules: true
        paths:
        - src
site_name: Cloudmesh AI Vpn
theme:
  favicon: assets/favicon.ico
  logo: assets/logo-white.png
  name: material
use_directory_urls: false
